---
name: Testing

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md
jobs:
  unit-test-linux:
    name: Linux unit tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: Validate code
        run: make validate

      - name: Running unit tests
        run: make test-coverage

      - name: Install gcov2lcov
        working-directory: /tmp
        run: go get -u github.com/jandelgado/gcov2lcov

      - name: Convert coverage.out to lcov.info
        run: gcov2lcov -infile=coverage.out -outfile=lcov.info

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: lcov.info
          flag-name: run-linux
          parallel: true

  harvest-test-linux:
    name: Linux harvest tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-16.04 ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then # if matrix.os == 'ubuntu-latest'
            sudo apt install musl-dev
          fi

      - name: Running Harvest tests
        run: make linux/harvest-tests

  unit-test-windows:
    name: Windows unit tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: Download deps
        run: go mod vendor

      - name: Running unit tests
        run: .\build\win_build.ps1 -skipBuild

  proxy-tests-linux:
    name: Proxy tests
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Running proxy tests
        run: make proxy-test

  build-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: Build linux agent
        run: make clean linux/amd64

      - name: Build container agent
        run: make -C build/container/ build/base

  finish:
    needs: [ unit-test-linux ]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  test-build:
    name: Test binary compilation for all platforms:arch
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: Build all platforms:arch
        run: make ci/build