---
name: Testing

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md
jobs:
  test-linux:
    name: Linux tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: Validate code
        run: make validate

      - name: Running unit tests
        run: make test-coverage

      - name: Install gcov2lcov
        working-directory: /tmp
        run: go get -u github.com/jandelgado/gcov2lcov

      - name: Convert coverage.out to lcov.info
        run: gcov2lcov -infile=coverage.out -outfile=lcov.info

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: lcov.info
          flag-name: run-linux
          parallel: true

  test-linux-harvest:
    name: Linux harvest tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Validate code
        run: linux/harvest-tests

  test-windows:
    name: Windows tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: Download deps
        run: go mod vendor

      - name: Running unit tests
        run: .\build\win_build.ps1 -skipBuild

  proxy-tests:
    name: Proxy tests
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Proxy Test
        run: make proxy-test

  build-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: Build linux agent
        run: make clean linux/amd64

      - name: Build container agent
        run: make -C build/container/ build/base

  finish:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
